title: DP PersonalJournal
description: A screen-reader accessible, password-protected personal journal for Windows.
baseurl: "/personal-journal"
url: "https://vlajna95.github.io"

theme: jekyll-theme-merlot

plugins:
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
